### ISSUE TITLE
Plots.jl @gif macro

### ISSUE THREAD

**Issue by ValdarT** [JunoLab/Weave.jl#105]
When using Plots.jl, currently when you create an [`Animation`](https://juliaplots.github.io/animations/) object with `@animate` macro and save it with `gif(...)` then the saved gif gets automatically linked into the document. I wouldn't quite expect that but why not.
However, output of `@gif` macro does not get automatically captured by `weave()` and this is something I would expect (and something that works with IJulia).

**Comment by mpastell** [comment]
It looks like you need to add a display method for AnimatedGif (https://github.com/JuliaPlots/Plots.jl/blob/d5e5d81ee2ce9de739eb31464a86c41fe60ca114/src/animation.jl#L104) to https://github.com/mpastell/Weave.jl/blob/master/src/plots.jl . 

I will keep this in mind, but a pull request would also be welcome.

**Comment by mpastell** [comment]
This works with current master, I'm not sure if its due to changes in Weave or Plots.

This works using https://gist.github.com/mpastell/8738b3e61639264ff2b8a6b092506fc0

```julia
weave("plots_anims.jl")
```

**Comment by mpastell** [comment]
I made the gifs embedded to HTML with the last commit.

**Comment by mosiman** [comment]
I also need to add `import Base64:stringmime`. Additionally, the gifs do not embed themselves into resulting markdown file when using `doctype = "pandoc"` (I often use this because pandoc's markdown has many more features than Julia's markdown)

**Comment by swairshah** [comment]
> This may be a problem again. I get a "stringmime not defined" error instead of the animation in the HTML. Adding `import Base64:stringmime` to the plots.jl file locally got it working again for me.

@tobydriscoll How do you find the local plots.jl file where I need to add the import? I also get the same error.

**Comment by tobydriscoll** [comment]
Try 
```
using Weave; pathof(Weave)
```
In older versions of julia you can use `Pkg.dir`.

**Comment by aviatesk** [comment]
this should be fixed in the latest version of Weave.
