### ISSUE TITLE
SystemError with Gadfly plots when Cairo is not installed

### ISSUE THREAD

**Issue by phipsgabler** [JunoLab/Weave.jl#121]
I couldn't use Gadfly plotting in Weave, there always occurs some IO error. Below is a reproduction with one of the example documents (with some deprecation warnings and precompilations cut out):

```
julia> weave("FIR_design.jl")
INFO: Weaving chunk 1 from line 34
WARNING: Method definition display(Weave.Report, Base.MIME{Symbol("image/png")}, Gadfly.Plot) in module Weave at /home/philipp/.julia/v0.6/Weave/src/gadfly.jl:6 overwritten at /home/philipp/.julia/v0.6/Weave/src/gadfly.jl:6.
WARNING: Method definition display(Weave.Report, Base.MIME{Symbol("image/svg+xml")}, Gadfly.Plot) in module Weave at /home/philipp/.julia/v0.6/Weave/src/gadfly.jl:13 overwritten at /home/philipp/.julia/v0.6/Weave/src/gadfly.jl:13.
INFO: Weaving chunk 2 from line 60
INFO: Weaving chunk 3 from line 74
INFO: Weaving chunk 4 from line 74
WARNING: ERROR: ErrorException occurred, including output in Weaved document
WARNING: Something went wrong during weaving
SystemError("opening file /tmp/tmpb2Y3fK/FIR_design_4_1.png", 2, nothing)
```

Another thing is that, while Gadfly normally works and plots to HTML, it doesn't anymore if I call it after having called `weave`, but instead gives the following output:

```
julia> plot(x = 1:10, y = rand(10), Geom.point)
Error showing value of type Gadfly.Plot:
ERROR: Cairo and Fontconfig are necessary for the PNG backend. Run:
  Pkg.add("Cairo")
  Pkg.add("Fontconfig")
You also have to delete /home/philipp/.julia/lib/v0.6/Compose.ji
and restart your REPL session afterwards.

Stacktrace:
 [1] display(::Weave.Report, ::Gadfly.Plot) at /home/philipp/.julia/v0.6/Weave/src/display_methods.jl:46
 [2] display(::Gadfly.Plot) at ./multimedia.jl:194
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:144
 [5] print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:129
 [6] (::Base.REPL.#do_respond#16{Bool,Base.REPL.##26#36{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:646
```
This gave me the hint that I was missing Cairo, and I as recommended there, I installed it with

```
Pkg.add("Cairo")

shell> rm ~/.julia/lib/v0.6/Compose.ji
```

Then it worked.

Now, I could have [read](http://weavejl.mpastell.com/stable/getting_started/) about the dependencies first, but that Weave output didn't make me think of a missing dependency... So, maybe either highlighting the Cairo dependency more in the docs, or providing better error messages for this case would be appropriate.

---

Another thing. While it works now, I don't quite get why the error should occur at all. Gadfly by default produces SVG output, without needing Cairo, why doesn't Weave just use that? For weaving to HTML I'd even prefer SVG to PNG. 

Otherwise: great package, thanks for making it!

**Comment by mpastell** [comment]
The default output is png because SVG files become very big when you plot even medium datasets. I'll look try to look into the error message when I have time.
