### ISSUE TITLE
Documentation - Broken Links

### ISSUE THREAD

**Issue by RoyiAvital** [JunoLab/Weave.jl#198]
Hello,

Found some broken links in documentation of version `0.9`:

 * [Getting Started Page](http://weavejl.mpastell.com/stable/getting_started/) - Link to [FIR_design.pdf](http://weavejl.mpastell.com/stable/examples/FIR_design.pdf).
 * [Publishing to HTML and PDF](http://weavejl.mpastell.com/stable/publish/) - Link to - [`FIRdesignplots.pdf`](http://weavejl.mpastell.com/stable/examples/FIR_design_plots.pdf).
 * [Publishing to HTML and PDF](http://weavejl.mpastell.com/stable/publish/) - Link to - [Julia MarkDown](http://docs.julialang.org/en/latest/manual/documentation.html#Markdown-syntax-1).

Thank You.

**Comment by mortenpi** [comment]
The last one should point to `https://docs.julialang.org/en/v1/stdlib/Markdown/` nowadays.

**Comment by thofma** [comment]
Still broken. When getting started, I would really like to see the PDF example ([FIR_design.pdf](http://weavejl.mpastell.com/stable/examples/FIR_design.pdf)) from the documentation.

**Comment by tlnagy** [comment]
It looks like @mpastell turned off PDF generation when building the docs in https://github.com/mpastell/Weave.jl/commit/4e70d32901271a7c870060eadcd8448753d138c9. Not sure why

**Comment by jlperla** [comment]
@tlnagy we have had no luck getting contact with Matti for 3 months now for PRs, etc. Do you have commit privileges, and are taking over some of the maintainer burden?

**Comment by tlnagy** [comment]
Yeah, I think Matti is swamped right now. I do have commit privileges and can make time to review critical PRs. Are there any that you specifically need?

**Comment by jlperla** [comment]
@tlnagy you have been added to the main problem, which is a serious regression. That said, it is worth discussing to make sure the cure doesn't break other setups

**Comment by mpastell** [comment]
Building pdfs requires Latex installation on Travis, I just haven’t had time to set it up.
