### ISSUE TITLE
endash not found

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/Weave.jl#222]
Using an endash (–) results in the following LaTeX error:
```
! Undefined control sequence.
<argument> \endash 
                   
l.125 ...er\ensuremath{\endash}Hopf, and numerics}
```

**Comment by tlnagy** [comment]
See @mpastell's reply here: https://github.com/JunoLab/Weave.jl/issues/150#issuecomment-458661711 

I'm going to close this in lieu of that issue.

**Comment by dlfivefifty** [comment]
Ah, completely forgot about that conversation
