### ISSUE TITLE
`@__FILE__` doesn't report current file in weaving context

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Weave.jl#263]
when loading data it's often convenient to use `@__FILE__` to reference files relative to the current file. During weaving that macro seems to evaluate to `"none"` though.

**Comment by kdheepak** [comment]
Additionally `@__DIR__` is the current working directory path instead of the directory the file is located in.

**Comment by pfitzseb** [comment]
Just for the record -- we'll need to wrap everything Weave evaluates in something like [`CodeTools.withpath`](https://github.com/JunoLab/CodeTools.jl/blob/db3edf47c596a393ce745e8a4185f0c08b14c317/src/utils.jl#L24-L36).

**Comment by kdheepak** [comment]
Weave uses `Core.eval` in a `SandBox` module to evaluate expressions from the various formats after converting them into chunks.

https://github.com/JunoLab/Weave.jl/blob/72e7ccfe8ac68c7dfc1ecd0c77b93de81cd5f3c0/src/run.jl#L235

We wouldn't be able to use [`CodeTools.withpath`](https://github.com/JunoLab/CodeTools.jl/blob/db3edf47c596a393ce745e8a4185f0c08b14c317/src/utils.jl#L24-L36) for this, right?

**Comment by aviatesk** [comment]
my hunch is adding something like [this](https://github.com/JunoLab/Atom.jl/pull/329) on [`eval_chunk`](https://github.com/JunoLab/Weave.jl/blob/b8b9b095b7d2196a04fb8d2b868743b5143d55ba/src/run.jl#L271) will solve the problems.

I set this issue as a milestone for v0.11.

**Comment by pfitzseb** [comment]
Yeah. Can also use something like https://github.com/JuliaDocs/DocumentationGenerator.jl/blob/d3c3ce4aa1dc9e3c813ac26d81023dda9d3dfc62/src/utils/rewrite.jl#L109-L117 if you don't want the dep on MacroTools.
