### ISSUE TITLE
Passing Front Matter

### ISSUE THREAD

**Issue by Nosferican** [JunoLab/Weave.jl#265]
## Feature request
Having someway to pass front matter from a `.jmd` to a `.md`.
## Use case
When writing a webpage, the markdown files may require certain front matter, however this has to be added manually after knitting the file every time.

**Comment by tpoisot** [comment]
This was also in #197 from about a year ago - but this got literatly 0 feedback from the devs

**Comment by aviatesk** [comment]
dup of #197
