### ISSUE TITLE
Weave does not run on julia 1.3.1

### ISSUE THREAD

**Issue by j-fu** [JunoLab/Weave.jl#267]
Hi, after updating to 1.3.1, weave does not run anymore. It seems the problem
is linked to using Requires (see [weave-err.txt](https://github.com/JunoLab/Weave.jl/files/4014199/weave-err.txt)). If I comment out `using Requires` and `__init__` , that particular error vanishes.

Jürgen

**Comment by aviks** [comment]
Given that upstream issue in Requires is closed, this can be closed as well?

**Comment by j-fu** [comment]
Yes.
