### ISSUE TITLE
Interactive HTML output giving errors on plotly() and plotlyjs()

### ISSUE THREAD

**Issue by ElectronicTeaCup** [JunoLab/Weave.jl#275]
I am getting issues when I try to get an html output with plotly backend. When I put in the following:

```
using Plots
plotly()
plot(rand(10))
```
And then output via weave using:

`weave((“doctest.jmd”), out_path=:pwd,doctype=“md2html”)`

I get this:
![image](https://user-images.githubusercontent.com/31346583/73941319-5775ac00-48ed-11ea-80b6-30ce028757f7.png)

Error:
```
[ Info: Weaving chunk 1 from line 7
┌ Warning: ERROR: BoundsError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/UOxmI/src/run.jl:243
[ Info: Report weaved to test.html
[ Info: Weaving chunk 1 from line 7
┌ Warning: ERROR: BoundsError occurred, including output in Weaved document
└ @ Weave ~/.julia/packages/Weave/UOxmI/src/run.jl:243
[ Info: Report weaved to test.html
```
 

With plotlyjs():

![image](https://user-images.githubusercontent.com/31346583/73941355-68262200-48ed-11ea-8d8f-fc0c0401414b.png)

gr() is working fine.

**Comment by ElectronicTeaCup** [comment]
Working with updated Julia version (was on [1.0.3](https://packages.debian.org/buster/julia) before on Debian). Installed JuliaPro and used the Julia (1.2.0) that came with it.

**Comment by ElectronicTeaCup** [comment]
Having this issue again, also I'm unable to get plotly() plots in the Juno plots pane, perhaps [this issue](https://github.com/JuliaPlots/Plots.jl/issues/2704) is related?

**Comment by aviatesk** [comment]
work for me. can you follow our new issue template and share your environment info ?

**Comment by ElectronicTeaCup** [comment]
Yes, will close this and make a new issue
