### ISSUE TITLE
YAML Frontmatter in output file

### ISSUE THREAD

**Issue by JonasIsensee** [JunoLab/Weave.jl#299]
Hi,

I use Weave to convert and run jupyter-notebooks to markdown for a static jekyll site.

Long story short: I need my output (markdown) files to have YAML frontmatter.
However, so far any YAML that I include in the notebook is automatically parsed as a header during the weaving and then discarded.

Is there currently any way to achieve what I described?
If not, I would very much appreciate any hints on how to implement this.
(I'm happy to have a go at this myself)

**Comment by aviatesk** [comment]
dup of https://github.com/JunoLab/Weave.jl/issues/197.
