### ISSUE TITLE
Missing markdown output with YAML header

### ISSUE THREAD

**Issue by michakraus** [JunoLab/Weave.jl#304]
I am trying to create some slides using Weave.jl and Remark.jl. When I have a YAML header, I am missing slides in the markdown output. For example, weaving the file

````
---
title: "myTitle"
author: "myAuthor"
---

# myTitle

## mySubtitle

myAuthor

myDate


---

## Hello World


```julia
println("Hello")
```
````

with
````
Weave.weave("test.jmd", out_path = "build", doctype = "github")
````

produces the output

`````
## Hello World


````julia
println("Hello")
````


````
Hello
````

`````

When removing the YAML header,
````

# myTitle

## mySubtitle

myAuthor

myDate


---

## Hello World


```julia
println("Hello")
```

````

the output contains both slides
`````

# myTitle

## mySubtitle

myAuthor

myDate


---

## Hello World


````julia
println("Hello")
````


````
Hello
````


`````

I am using Julia v1.4.0 and Weave v0.9.4.

**Comment by aviatesk** [comment]
dup of https://github.com/JunoLab/Weave.jl/issues/197

**Comment by michakraus** [comment]
This is not a dup of #197. The problem is not that the header is stripped, but that the piece between the header and `## Hello World` is stripped.

**Comment by aviatesk** [comment]
ah I see. I just found the existing header striping logic is kinda awful and now trying to fix this, but lets's keep this open until it's solved.

**Comment by michakraus** [comment]
It seems adding an empty julia block to the first slide works around this issue, i.e., 
````
---
title: "myTitle"
author: "myAuthor"
---

```julia
```

# myTitle

## mySubtitle

myAuthor

myDate


---

## Hello World


```julia
println("Hello")
```
````
produces correct results.
