### ISSUE TITLE
[BUG] fig_path gets overwritten for 2html doctypes

### ISSUE THREAD

**Issue by feanor12** [JunoLab/Weave.jl#358]
Using fig_path when weaving to  md2html does not work

```julia
(@v1.4) pkg> status Weave
Status `C:\Users\mpus\.julia\environments\v1.4\Project.toml`
  [44d3d7a6] Weave v0.10.2
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\mpus\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 2
```

Example:
test.jmd
```tex
    ```julia 
    using Plots
    plot(rand(10))
    ```
```
REPL
```julia
weave("test.jmd", doctype="md2html", out_path= joinpath(pwd(),"out"),cache=:all,fig_path="fig")
readir("out")
```
Output of readdir:
```
3-element Array{String,1}:
 "cache"
 "jl_tG4P2M"
 "test.html"
```

The folder  "jl_tG4P2M" is created instead of fig.
Also if I rerun the command to weave I get a new random folder.
This is a problem when I am running weave in a loop to update my html file as I create a lot of folders.

I think the reason can be found here https://github.com/JunoLab/Weave.jl/blob/1e9ba19db499675b3201d0d700a8ab14e2f801ed/src/run.jl#L50-L54

As far as I understand it the fig_path parameter is overwritten without giving an warning or an option to avoid it.

Would it be possible to use the same folder or clear it after the run?

**Comment by aviatesk** [comment]
yeah, it seems like a bug. Well, those temporary folders will be cleaned up after you exited a running session, but we should respect given `fig_path` I think.

**Comment by aviatesk** [comment]
can you try `] add Weave#master` and report back ?

**Comment by feanor12** [comment]
Seems to work :+1:
