### ISSUE TITLE
Breaking change to argument parsing in Weave was not tagged as a breaking change

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Weave.jl#422]
See https://buildkite.com/julialang/scimlbenchmarks-dot-jl/builds/85#d245dbcd-7d88-4272-9409-70ad5b3626e7/147-231

https://github.com/SciML/SciMLBenchmarks.jl/blob/0a725726e0a62de00d94d880502c7712ae310771/benchmarks/test.jmd

That form `julia{echo=false}` was accepted for years, but now has been removed without a breaking release. That should get reverted.

**Comment by pfitzseb** [comment]
Fixed in 0.10.8.
