### ISSUE TITLE
[FR] Would it be useful to allow Julia code run in `shell` and `Pkg` mode?

### ISSUE THREAD

**Issue by einzigsue** [JunoLab/Weave.jl#460]
Would it be useful to allow Julia code run in `shell` and `Pkg` mode?
Hi @pfitzseb 

Would it be useful to allow julia markdown code blocks that run in `shell` and `Pkg` mode?

For example, allow section like below to run status in the package manager 
```julia
] st
```
and to execute command such as pwd in shell mode 
```julia
; pwd
```

Cheers,
Yue

**Comment by pfitzseb** [comment]
The issue with this approach is that it generates files that are specific to the extension -- you can't just `include` them.
